### ISSUE TITLE
EHR Vendor asked only once

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#119]
We had a coach in charge of (database ID #) 18268 who noted that their EHR Vendor, listed on the front page of their Practices list, was out of date.

We only ask EHR Vendor at the first in-person visit, so there's nowhere to update this information.  Do we want to surface this question more often, and display the most recent EHR Vendor?  Do we remove EHR Vendor from the Practices list?  Do we relabel it "Original EHR Vendor"?  Do we care?

**Comment by seemack** [comment]
Maybe we'll surface EHR Vendor in each in-person (or other) visit?

**Comment by kuoxes1** [comment]
Similar so how we frontload pdsas, prepopulate a NEW variable set for ANY contact.

This variable looks like the EHR window you see at the welcome visit, just prepopulated with prior data.  If no changes are made, the old data saves with this visit.

Note that this doesn't add any work for coaches since its prepopulated.

**Comment by seemack** [comment]
Added. Defaults to last entered EHR Vendor.
