### ISSUE TITLE
survey tracking

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#146]
Can you add  date of visit to the survey T2 tracking page, and then add that date field to the export? 

Thanks!

**Comment by seemack** [comment]
T2 is 5th in-person required monthly visit.  Add to Survey Status Export (Mgr View).

Also include Survey Monkey links.

Add Total Links (#5 in T2 Survey) to SS Export, too.

**Comment by kuoxes1** [comment]
Also please add to the export: the name and email of primary contact thanks!!!

**Comment by kuoxes1** [comment]
Primary contact appears, but still need:
email
address
fax

**Comment by seemack** [comment]
Add primary contact email address to Survey Status Export (Manager View).
Add clinic address.
Add fax number.

**Comment by seemack** [comment]
Add sms2_totalnumber to Survey Status Export, title SMS Total Returned.

**Comment by seemack** [comment]
Add coach email to Survey Status Export (manager view)

**Comment by kuoxes1** [comment]
I see coach email THANKS!

Still need (less urgently)
SMS2 # returned (from the EXCEL upload I do)
address and fax of the practice (from the database)

**Comment by seemack** [comment]
Address & fax are out there.  Quick questions so I can wrap this up.

(1) Which variable is SMS2 # returned?  Is it 'sms2_totalnumber'?
(2) 'ps2_notes' and 'sms2_notes' are the variables previously called ps_notes & sms_notes, right?
(3) Since I have to go in & make changes anyway, do you need any of these new fields:  ps2_date_de, ps2_dataentrynotes, sms2_date_de.
