### ISSUE TITLE
IV contacts qualitative data export

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#51]
Clarissa wants IV tracker data for her needs.
1.  How fresh does it have to be
2. How frequently will she download it
3. What are the specific variables?

Elena will follow up with Clarissa to flesh out, but this is low priority for now.

**Comment by rpardee** [comment]
Consider having Chris or me at this meeting, and maybe getting a demo of the mechanics of bringing data into the qualitative analysis tool (ATLAS, was it?).

**Comment by rpardee** [comment]
Alas, I lost my notes from yesterday's meeting.  Here's what I can remember:

1. Clarissa wants a text (optimally rich text--that's what ATLAS will want)
2. File should contain all intervention contacts (of all types) ocurring between start and stop dates she specifies, for an organization (e.g., ORPRN or Qualis) she specifies.
3. She expects to run the export on a monthly basis.
4. The report should contain:
  1. Practice ID (nee StudyID)
  2. Practice Name
  3. Contact Date
  4. Name of the coach making the contact (I think?)
  5. Type of contact (in-person, e-mail, etc.)
  5. All open-ended fields (TODO: enumerate these).
5. Report order is by:
  1. Practice Name
  2. Contact Date

Note that this report will *not* serve Erika's need for ongoing monitoring of coach activities for use in her supervision.  We did not get too far into her needs.  I suppose it would be naive to expect that the existing IV contacts (fourth link [on this page](http://healthy-hearts-northwest.herokuapp.com/admin_area)) would serve her?

**Comment by squabwrangler** [comment]
Clarification: that need in Roy's "Note" above is for Nicole (get it right, man!) She said that the existing export would be fine.

The only other thing that I would add to Clarissa's list (#4) is    vii. duration of contact
Otherwise, what you have is accurate. Open ended fields include: Observations/dynamics of clinic, PDSA section, HIT tier explain, GYR comments, Comments/Field notes.

**Comment by rpardee** [comment]
Dadgummit--I'm sorry.  I hereby undertake to learn everybody's name. :(

Thanks for the added detail!

**Comment by seemack** [comment]
Additional comments from Elena's email 3/31:

I talked to Clarissa this am and she wants to be able to enter in a date range for the report and have it export only records from that date range.
She wants have the report display preferrably in a word table instead of excel
She wants it sorted first by orprn/qualis then by coach then by practice then by date.

**Comment by seemack** [comment]
Plan for Clarissa:  I'll start by building text exports of each IV Contact for import into Atlas.  Likely we'll have to change that to RTF or some other format that allows for easier bolding, headers, etc.  To avoid the lack of a file server, I'm hoping to roll each of the files into a zip archive that can be downloaded just once - maybe with [ZipRuby](https://bitbucket.org/winebarrel/zip-ruby/wiki/Home).  Otherwise we may need to pay for some space on a file server (AWS?).

**Comment by seemack** [comment]
Clarissa comments from 4/18:

The first thing I realized is that I think we need to build in some code to exclude any record/entry that don’t have data in the open ended fields.  A bunch of these don’t have any actual qualitative data in them.  

Other asks I have (these are trying to get us step wise toward the pretty version, trying to find some middle ground if possible): 1) I would like double returns between each separate data field and a single return between the field name and the data, 2) Is there a way to get these to auto name based on some key data, like a naming convention that consists of coach last name, practice number and data of contact?, and 3) at some point are you going to build a search interface that would allow me to delineate the records I would be pulling.  If so how hard would be to expand that capacity from just dates to add 2-3 more variables such as coach and practice?  

GYR text data seems to be missing.  [Is it actually missing or just not populated in dev? - check]

**Comment by seemack** [comment]
I’ve added the carriage returns you’ve requested.  I’ve also limited exports to folks with qualitative data.  Please take a look.

Right now the individual files are named based on their underlying (database) identifier, but we can change that.  My thoughts on this are:
•	Coach names aren’t broken into first v. last, but we have full name, or I could parse it and extract the last name (in most cases)
•	The combination of name-practice ID-date may not be unique, which won’t work. Since the database identifier *is* unique, I could include that as a fourth part of the name
•	Practice IDs are assigned when they return their PAL, but some practices could have comments data from contacts prior to this. Do you want this data?

I definitely can build a search page, although if the file names already contain all your search parameters, it may not (or may) be a top priority.  I’m inclined to do this part last, after we’ve determined that the files being created work properly for you and in Atlas.ti.

The GYR data is there, it’s just blank for all our test cases.  I’d encourage to create your own test practice (or ask someone to do it for you) to make sure you’re comfortable that everything is being exported properly.

**Comment by seemack** [comment]
From Clarissa:

The only additional formatting request I would have is that the field names be bolded and the content remain plain text.  Otherwise these are easy to read as is.  I was still getting records without qualitative content.  Is that because they had something like a name filled in?  Can we exclude those with qualitative content in things like the practice name field, basically those descriptive fields.  I can give you a list of those where content would qualify.  I’m not sure how much of an issue this will be for the real data, but if there are a lot of recorder/entries with no qualitative data it would be nice to run a periodic analysis of how many records have qualitative content.    

I think your plan for naming convention sounds great, ie adding the unique database recorder number.  I think the full name of the coach is fine.  For you last question, I guess if is in the IV tracker and has qualitative data I want it.  I don’t want anything from the recruitment side of the database.

**Comment by squabwrangler** [comment]
Chris to email Clarissa to go over this, include Erika.

**Comment by kuoxes1** [comment]
Clarissa has a few issues after meeting with Chris on 5/17:
1. Says contact, can it say Qual as the header?
2. GYR color field isn't in the export and needs to be
3.  rename fieldnotes to be  comments/fieldnotes  and put last
4.  only download by date, QUALIS/ORPRN, and coach criteria

**Comment by squabwrangler** [comment]
One more thing about this: Data in the comments section of some of the visits have odd characters embedded like this below, do you know why?:

"Smoking cessation asks smoking status from the past 2 yearsï‚§	Many patients, nonsmokers, had been asked over two years ago and their status didnâ€™t change over those yearsâ€¢	Providers and staff never indicated any updatesâ€”that this discussion occurredâ€”so these patients are falling out of the measure (this was discovered through chart audits)ï‚§	MAs are now being trained to note (date stamp) these updates in the EHRâ€”that the discussion did, in fact, occurâ€”â€œTreated as another vitalâ€â€¢	â€œYou see, when reviewing the charts, that the doctor obviously discussed smoking, but they didnâ€™t bill for counseling or order medsâ€â€”didnâ€™t meet measure o"

**Comment by vanborkulo** [comment]
My guess is this has to do with the fact that coaches sometimes cut and paste from other notes they've done.

**Comment by kuoxes1** [comment]
change formatting - priority 1
change to have a separate page to sort by criteria  is priority 3

**Comment by seemack** [comment]
GYR color added and Comments moved to the end of the export.  We should be able to demote this to a lower priority now.

**Comment by seemack** [comment]
Closing this basic Qual Export request.  The search parameters addition has moved to issue #101 .
