### ISSUE TITLE
Data entry discrepancies cause improperly calculated quarterly visits

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#72]
Quarterly visits increment sequentially, so the first "Quarterly In-Person Visit" is baseline, the second one is Q2, etc. But if one of these required visits is double entered, the count will increment incorrectly and must be deleted and fixed manually.  Similarly, if the data entry for the visits is done out of order, the visit counter will populate out of order.

In either case, if there are more than 5 such visits, the system will continue to increment the count, though much of the logic about what to display on the New Contact page was defined by assuming there were just 5 visits in a particular order.

This was pointed out long ago, but the concerns were clearly dismissed too quickly - it was decided to prioritize the convenience of not forcing the users to calculate a visit number.  But now we have at least one instance of this double entry.  To turn this kvetching into actionable items:

1. Will ORPRN (or anyone) have more than 5 visits considered "Quarterly In-Person Visits"?
2. If not, is the potential for double entry or out-of-order entry high enough to require the visit number to be entered by our partners, rather than automatically calculated? 

![image](https://cloud.githubusercontent.com/assets/355833/14000641/4bddb2ce-f0ff-11e5-8fa4-c75bcd644a77.png)

**Comment by vanborkulo** [comment]
Easiest to talk about this. I am out of the office until tomorrow AM. Can I catch you then?

Sent from my iPhone

On Mar 23, 2016, at 1:56 PM, Christopher Mack <notifications@github.com<mailto:notifications@github.com>> wrote:


Quarterly visits increment sequentially, so the first "Quarterly In-Person Visit" is baseline, the second one is Q2, etc. But if one of these required visits is double entered, the count will increment incorrectly and must be deleted and fixed manually. Similarly, if the data entry for the visits is done out of order, the visit counter will populate out of order.

In either case, if there are more than 5 such visits, the system will continue to increment the count, though much of the logic about what to display on the New Contact page was defined by assuming there were just 5 visits in a particular order.

This was pointed out long ago, but the concerns were clearly dismissed too quickly - it was decided to prioritize the convenience of not forcing the users to calculate a visit number. But now we have at least one instance of this double entry. To turn this kvetching into actionable items:

  1.  Will ORPRN (or anyone) have more than 5 visits considered "Quarterly In-Person Visits"?
  2.  If not, is the potential for double entry or out-of-order entry high enough to require the visit number to be entered by our partners, rather than automatically calculated?

�
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub<https://github.com/seemack/healthy-hearts-northwest-dev/issues/72>

________________________________

GHC Confidentiality Statement

This message and any attached files might contain confidential information protected by federal and state law. The information is intended only for the use of the individual(s) or entities originally named as addressees. The improper disclosure of such information may be subject to civil or criminal penalties. If this message reached you in error, please contact the sender and destroy this message. Disclosing, copying, forwarding, or distributing the information by unauthorized individuals or entities is strictly prohibited by law.

**Comment by seemack** [comment]
Verified this is due to the data entered - the interventionist saved a record as "Quarterly In-Person," which incremented the in-person visit count.  This was corrected to 4 hours later to "Other Required" but the in-person visit count wasn't rolled back.

This is the same issue as #69 - not really an export issue, but an issue with the underlying data.

**Comment by seemack** [comment]
I'm going to surface the In-Person Visit Number field so it can be corrected as necessary.
